// packages/templates/src/registry/templates/workflow/api/index.ts

export const workflowTriggerTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
import type { NextApiRequest, NextApiResponse } from 'next';
import { getAuth } from '@clerk/nextjs/server';
import { workflowExecutor } from '@/lib/workflow-executor';
import { workflowDef } from '@/lib/workflows/{{WORKFLOW_NAME}}';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { userId, orgId } = getAuth(req);
  if (!userId || !orgId) return res.status(401).json({ error: 'Unauthorized' });

  // Match trigger
  if (req.method !== workflowDef.trigger.type && workflowDef.trigger.type === 'webhook') {
    if (workflowDef.trigger.method !== 'POST') {
      return res.status(405).json({ error: 'Method not allowed by workflow trigger' });
    }
  }

  try {
    const run = await workflowExecutor.startRun(
      workflowDef,
      req.query['appId'] as string ?? 'default',
      orgId,
      req.body ?? {}
    );
    return res.status(202).json({ runId: run.runId, status: run.status });
  } catch (error) {
    console.error('Workflow trigger error:', error);
    return res.status(500).json({ error: 'Failed to trigger workflow' });
  }
}
`;

export const workflowExecuteTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
import type { NextApiRequest, NextApiResponse } from 'next';
import { getAuth } from '@clerk/nextjs/server';
import { workflowExecutor } from '@/lib/workflow-executor';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { userId, orgId } = getAuth(req);
  if (!userId || !orgId) return res.status(401).json({ error: 'Unauthorized' });

  if (req.method === 'GET') {
    const { runId } = req.query;
    if (runId) {
      const run = workflowExecutor.getRun(runId as string);
      if (!run) return res.status(404).json({ error: 'Run not found' });
      return res.status(200).json({ run });
    }
    return res.status(400).json({ error: 'runId required' });
  }

  return res.status(405).json({ error: 'Method not allowed' });
}
`;
