// packages/templates/src/registry/templates/admin-panel/pages/index.ts

export const adminListTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
'use client';
import React, { useState } from 'react';
import useSWR from 'swr';
import Link from 'next/link';

interface AdminRow {
  id: string;
  {{FIELD_LIST}}
  createdAt: string;
}

interface ApiResponse {
  data: AdminRow[];
  meta: { page: number; total: number; totalPages: number };
}

const fetcher = (url: string) => fetch(url).then((r) => r.json());

export default function Admin{{ENTITY_NAME}}List() {
  const [page, setPage] = useState(1);
  const { data, isLoading, mutate } = useSWR<ApiResponse>(
    \`/api/admin/{{TABLE_NAME}}?page=\${page}&limit=25\`,
    fetcher
  );

  async function handleDelete(id: string) {
    if (!confirm('Delete this record? This cannot be undone.')) return;
    await fetch(\`/api/admin/{{TABLE_NAME}}/\${id}\`, { method: 'DELETE' });
    mutate();
  }

  return (
    <div className="p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <p className="text-xs text-gray-500 uppercase tracking-widest font-medium">Admin Panel</p>
          <h1 className="text-2xl font-semibold text-gray-900">{{ENTITY_NAME_PLURAL}}</h1>
        </div>
        <Link
          href="/admin/{{TABLE_NAME}}/new"
          className="px-4 py-2 bg-gray-900 text-white text-sm font-medium rounded-md hover:bg-gray-700"
        >
          + Add {{ENTITY_NAME}}
        </Link>
      </div>

      {isLoading ? (
        <div className="text-gray-400">Loading…</div>
      ) : (
        <>
          <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
            <table className="min-w-full text-sm divide-y divide-gray-100">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">ID</th>
                  {{FIELD_LIST}}
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Created</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {data?.data.map((row) => (
                  <tr key={row.id} className="hover:bg-gray-50">
                    <td className="px-4 py-3 font-mono text-xs text-gray-400">{row.id.slice(0, 8)}…</td>
                    {{FIELD_LIST}}
                    <td className="px-4 py-3 text-gray-500 text-xs">{new Date(row.createdAt).toLocaleDateString()}</td>
                    <td className="px-4 py-3 text-right">
                      <Link href={\`/admin/{{TABLE_NAME}}/\${row.id}\`} className="text-indigo-600 hover:underline mr-3 text-xs">Edit</Link>
                      <button onClick={() => handleDelete(row.id)} className="text-red-500 hover:text-red-700 text-xs">Delete</button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {data && data.meta.totalPages > 1 && (
            <div className="flex justify-between items-center mt-3 text-sm text-gray-500">
              <span>{data.meta.total} total records</span>
              <div className="flex gap-2">
                <button disabled={page === 1} onClick={() => setPage(p => p - 1)} className="px-3 py-1 border rounded disabled:opacity-40">Prev</button>
                <button disabled={page >= data.meta.totalPages} onClick={() => setPage(p => p + 1)} className="px-3 py-1 border rounded disabled:opacity-40">Next</button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
`;

export const adminUsersTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
'use client';
import React from 'react';
import useSWR from 'swr';

interface OrgMember {
  id: string;
  userId: string;
  role: string;
  identifier: string;
}

const fetcher = (url: string) => fetch(url).then((r) => r.json());

const AVAILABLE_ROLES = [{{ROLES}}];

export default function AdminUsersPage() {
  const { data, mutate } = useSWR<{ members: OrgMember[] }>('/api/admin/users', fetcher);

  async function updateRole(userId: string, newRole: string) {
    await fetch('/api/admin/users/role', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ userId, role: newRole }),
    });
    mutate();
  }

  return (
    <div className="p-6">
      <h1 className="text-2xl font-semibold text-gray-900 mb-6">User Management</h1>
      <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
        <table className="min-w-full text-sm divide-y divide-gray-100">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">User</th>
              <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Role</th>
              <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Change Role</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {data?.members.map((member) => (
              <tr key={member.id}>
                <td className="px-4 py-3">
                  <span className="font-medium text-gray-900">{member.identifier}</span>
                  <span className="block text-xs text-gray-400 font-mono">{member.userId.slice(0, 12)}…</span>
                </td>
                <td className="px-4 py-3">
                  <span className="px-2 py-0.5 bg-gray-100 text-gray-700 rounded text-xs font-medium">{member.role}</span>
                </td>
                <td className="px-4 py-3">
                  <select
                    value={member.role}
                    onChange={(e) => updateRole(member.userId, e.target.value)}
                    className="border border-gray-300 rounded text-xs px-2 py-1"
                  >
                    {AVAILABLE_ROLES.map((role: string) => (
                      <option key={role} value={role}>{role}</option>
                    ))}
                  </select>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
`;
