// packages/templates/src/registry/templates/workflow/pages/index.ts

export const workflowListTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
'use client';
import React, { useState } from 'react';
import useSWR from 'swr';

interface WorkflowRun {
  runId: string;
  workflowId: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  startedAt: string;
  completedAt?: string;
  error?: string;
  currentStep: number;
  stepResults: { stepIndex: number; type: string; status: string }[];
}

const fetcher = (url: string) => fetch(url).then((r) => r.json());

const STATUS_COLORS: Record<string, string> = {
  pending: 'bg-yellow-100 text-yellow-800',
  running: 'bg-blue-100 text-blue-800',
  completed: 'bg-green-100 text-green-800',
  failed: 'bg-red-100 text-red-800',
};

export default function {{WORKFLOW_NAME}}WorkflowManager() {
  const [triggering, setTriggering] = useState(false);
  const [payload, setPayload] = useState('{}');

  const { data: runs, mutate } = useSWR<{ runs: WorkflowRun[] }>('/api/workflows/runs', fetcher, {
    refreshInterval: 5000,
  });

  async function triggerWorkflow() {
    setTriggering(true);
    try {
      const parsedPayload = JSON.parse(payload);
      const res = await fetch('/api/workflows/trigger', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ payload: parsedPayload }),
      });
      if (!res.ok) throw new Error(await res.text());
      mutate();
      alert('Workflow triggered!');
    } catch (err) {
      alert(\`Trigger failed: \${err instanceof Error ? err.message : String(err)}\`);
    } finally {
      setTriggering(false);
    }
  }

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-semibold text-gray-900">{{WORKFLOW_NAME}} Workflows</h1>

      {/* Manual Trigger Panel */}
      <div className="bg-white border border-gray-200 rounded-lg p-5">
        <h2 className="text-lg font-medium text-gray-800 mb-3">Trigger Workflow</h2>
        <div className="space-y-3">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Payload (JSON)</label>
            <textarea
              value={payload}
              onChange={(e) => setPayload(e.target.value)}
              rows={3}
              className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>
          <button
            onClick={triggerWorkflow}
            disabled={triggering}
            className="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-md hover:bg-indigo-700 disabled:opacity-60"
          >
            {triggering ? 'Triggering…' : '▶ Run Now'}
          </button>
        </div>
      </div>

      {/* Run History */}
      <div className="bg-white border border-gray-200 rounded-lg p-5">
        <h2 className="text-lg font-medium text-gray-800 mb-4">Run History</h2>
        {!runs?.runs?.length ? (
          <p className="text-gray-400 text-sm">No workflow runs yet.</p>
        ) : (
          <div className="space-y-3">
            {runs.runs.map((run) => (
              <div key={run.runId} className="border border-gray-100 rounded-md p-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className={\`px-2 py-0.5 rounded-full text-xs font-medium \${STATUS_COLORS[run.status] ?? 'bg-gray-100 text-gray-600'}\`}>
                      {run.status}
                    </span>
                    <span className="text-sm text-gray-600 font-mono">{run.runId.slice(0, 20)}…</span>
                  </div>
                  <span className="text-xs text-gray-400">{new Date(run.startedAt).toLocaleString()}</span>
                </div>
                {run.error && (
                  <p className="mt-2 text-xs text-red-600 font-mono">{run.error}</p>
                )}
                <div className="mt-2 flex gap-1">
                  {run.stepResults.map((sr) => (
                    <span
                      key={sr.stepIndex}
                      title={\`Step \${sr.stepIndex}: \${sr.type} — \${sr.status}\`}
                      className={\`w-5 h-5 rounded-full text-xs flex items-center justify-center \${sr.status === 'success' ? 'bg-green-500' : sr.status === 'failed' ? 'bg-red-500' : 'bg-gray-300'}\`}
                    >
                      {sr.stepIndex + 1}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
`;
