// packages/templates/src/registry/templates/crud/pages/index.ts
// Template source strings for CRUD page files.
// Each export is a template string with {{SLOT}} markers replaced by the AST patcher.

export const listPageTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
'use client';
import React, { useState } from 'react';
import { useRouter } from 'next/router';
import useSWR from 'swr';
import Link from 'next/link';

interface {{ENTITY_NAME}}Row {
  id: string;
  {{FIELD_LIST}}
  createdAt: string;
  updatedAt: string;
}

interface ApiResponse {
  data: {{ENTITY_NAME}}Row[];
  meta: { page: number; limit: number; total: number; totalPages: number };
}

const fetcher = (url: string) => fetch(url).then((r) => r.json());

export default function {{ENTITY_NAME}}List() {
  const router = useRouter();
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');

  const { data, isLoading, mutate } = useSWR<ApiResponse>(
    \`/api/{{TABLE_NAME}}?page=\${page}&limit=20\${search ? \`&search=\${encodeURIComponent(search)}\` : ''}\`,
    fetcher
  );

  async function handleDelete(id: string) {
    if (!confirm('Delete this {{ENTITY_NAME}}?')) return;
    await fetch(\`/api/{{TABLE_NAME}}/\${id}\`, { method: 'DELETE' });
    mutate();
  }

  return (
    <div className="p-6">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-semibold text-gray-900">{{ENTITY_NAME_PLURAL}}</h1>
        <Link
          href="/{{TABLE_NAME}}/new"
          className="inline-flex items-center px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-md hover:bg-indigo-700 transition-colors"
        >
          + New {{ENTITY_NAME}}
        </Link>
      </div>

      <div className="mb-4">
        <input
          type="text"
          placeholder="Search {{ENTITY_NAME_PLURAL}}..."
          value={search}
          onChange={(e) => { setSearch(e.target.value); setPage(1); }}
          className="w-full max-w-xs border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
        />
      </div>

      {isLoading ? (
        <div className="text-gray-500 text-sm">Loading…</div>
      ) : (
        <>
          <div className="overflow-x-auto rounded-lg border border-gray-200">
            <table className="min-w-full divide-y divide-gray-200 text-sm">
              <thead className="bg-gray-50">
                <tr>
                  {{TABLE_COLUMNS}}
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-100">
                {data?.data.map((row) => (
                  <tr key={row.id} className="hover:bg-gray-50 transition-colors">
                    {{TABLE_COLUMNS}}
                    <td className="px-4 py-3 text-right whitespace-nowrap">
                      <Link href={\`/{{TABLE_NAME}}/\${row.id}\`} className="text-indigo-600 hover:underline mr-3">View</Link>
                      <button
                        onClick={() => handleDelete(row.id)}
                        className="text-red-500 hover:text-red-700"
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                ))}
                {data?.data.length === 0 && (
                  <tr>
                    <td colSpan={99} className="px-4 py-8 text-center text-gray-400">
                      No {{ENTITY_NAME_PLURAL}} found.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          {data && data.meta.totalPages > 1 && (
            <div className="flex items-center justify-between mt-4 text-sm text-gray-600">
              <span>Page {data.meta.page} of {data.meta.totalPages} — {data.meta.total} total</span>
              <div className="flex gap-2">
                <button
                  disabled={page === 1}
                  onClick={() => setPage((p) => p - 1)}
                  className="px-3 py-1 border border-gray-300 rounded disabled:opacity-40 hover:bg-gray-50"
                >
                  Previous
                </button>
                <button
                  disabled={page >= data.meta.totalPages}
                  onClick={() => setPage((p) => p + 1)}
                  className="px-3 py-1 border border-gray-300 rounded disabled:opacity-40 hover:bg-gray-50"
                >
                  Next
                </button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
`;

export const detailPageTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
'use client';
import React from 'react';
import { useRouter } from 'next/router';
import useSWR from 'swr';
import Link from 'next/link';

interface {{ENTITY_NAME}}Detail {
  id: string;
  {{FIELD_LIST}}
  createdAt: string;
  updatedAt: string;
}

const fetcher = (url: string) => fetch(url).then((r) => r.json());

export default function {{ENTITY_NAME}}Detail() {
  const router = useRouter();
  const { id } = router.query as { id: string };

  const { data, isLoading, error } = useSWR<{ data: {{ENTITY_NAME}}Detail }>(
    id ? \`/api/{{TABLE_NAME}}/\${id}\` : null,
    fetcher
  );

  async function handleDelete() {
    if (!confirm('Permanently delete this {{ENTITY_NAME}}?')) return;
    await fetch(\`/api/{{TABLE_NAME}}/\${id}\`, { method: 'DELETE' });
    router.push('/{{TABLE_NAME}}');
  }

  if (isLoading) return <div className="p-6 text-gray-500">Loading…</div>;
  if (error || !data?.data) return <div className="p-6 text-red-500">{{ENTITY_NAME}} not found.</div>;

  const item = data.data;

  return (
    <div className="p-6 max-w-2xl">
      <div className="flex items-center justify-between mb-6">
        <div>
          <Link href="/{{TABLE_NAME}}" className="text-indigo-600 hover:underline text-sm">← Back to {{ENTITY_NAME_PLURAL}}</Link>
          <h1 className="text-2xl font-semibold text-gray-900 mt-1">{{ENTITY_NAME}} Detail</h1>
        </div>
        <div className="flex gap-2">
          <Link
            href={\`/{{TABLE_NAME}}/\${id}/edit\`}
            className="px-4 py-2 border border-gray-300 rounded-md text-sm hover:bg-gray-50"
          >
            Edit
          </Link>
          <button
            onClick={handleDelete}
            className="px-4 py-2 bg-red-600 text-white text-sm rounded-md hover:bg-red-700"
          >
            Delete
          </button>
        </div>
      </div>

      <div className="bg-white rounded-lg border border-gray-200 divide-y divide-gray-100">
        {{FIELD_LIST}}
        <div className="px-4 py-3 flex justify-between text-sm">
          <span className="text-gray-500 font-medium">Created</span>
          <span className="text-gray-900">{new Date(item.createdAt).toLocaleString()}</span>
        </div>
        <div className="px-4 py-3 flex justify-between text-sm">
          <span className="text-gray-500 font-medium">Updated</span>
          <span className="text-gray-900">{new Date(item.updatedAt).toLocaleString()}</span>
        </div>
      </div>
    </div>
  );
}
`;

export const formPageTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
'use client';
import React from 'react';
import { useRouter } from 'next/router';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import Link from 'next/link';

// ── Zod schema (slot-injected) ────────────────────────────────────────────────
const {{ENTITY_NAME}}Schema = z.object({
  {{ZOD_SCHEMA}}
});

type {{ENTITY_NAME}}Input = z.infer<typeof {{ENTITY_NAME}}Schema>;

export default function {{ENTITY_NAME}}Form() {
  const router = useRouter();
  const { id } = router.query as { id?: string };
  const isEdit = Boolean(id);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
    reset,
  } = useForm<{{ENTITY_NAME}}Input>({
    resolver: zodResolver({{ENTITY_NAME}}Schema),
  });

  // Load existing data for edit mode
  React.useEffect(() => {
    if (!isEdit || !id) return;
    fetch(\`/api/{{TABLE_NAME}}/\${id}\`)
      .then((r) => r.json())
      .then((json) => { if (json.data) reset(json.data); });
  }, [id, isEdit, reset]);

  async function onSubmit(values: {{ENTITY_NAME}}Input) {
    const url = isEdit ? \`/api/{{TABLE_NAME}}/\${id}\` : '/api/{{TABLE_NAME}}';
    const method = isEdit ? 'PATCH' : 'POST';

    const res = await fetch(url, {
      method,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(values),
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      alert(err.error ?? 'An error occurred. Please try again.');
      return;
    }

    router.push('/{{TABLE_NAME}}');
  }

  return (
    <div className="p-6 max-w-xl">
      <div className="mb-6">
        <Link href="/{{TABLE_NAME}}" className="text-indigo-600 hover:underline text-sm">← Back to {{ENTITY_NAME_PLURAL}}</Link>
        <h1 className="text-2xl font-semibold text-gray-900 mt-1">
          {isEdit ? 'Edit' : 'New'} {{ENTITY_NAME}}
        </h1>
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="bg-white rounded-lg border border-gray-200 p-6 space-y-4">
        {{FORM_FIELDS}}

        <div className="flex gap-3 pt-2">
          <button
            type="submit"
            disabled={isSubmitting}
            className="px-5 py-2 bg-indigo-600 text-white text-sm font-medium rounded-md hover:bg-indigo-700 disabled:opacity-60 transition-colors"
          >
            {isSubmitting ? 'Saving…' : isEdit ? 'Save Changes' : 'Create {{ENTITY_NAME}}'}
          </button>
          <Link
            href="/{{TABLE_NAME}}"
            className="px-5 py-2 border border-gray-300 text-sm rounded-md hover:bg-gray-50"
          >
            Cancel
          </Link>
        </div>
      </form>
    </div>
  );
}
`;
