// packages/templates/src/registry/templates/admin-panel/api/index.ts

export const adminCrudTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
import type { NextApiRequest, NextApiResponse } from 'next';
import { getAuth } from '@clerk/nextjs/server';
import { getTenantPrisma } from '@/lib/db/tenant';

// Admin-only: requires 'admin' or 'super_admin' org role
const ADMIN_ROLES = [{{ROLES}}];

function isAdmin(orgRole: string | null | undefined): boolean {
  return ADMIN_ROLES.includes(orgRole ?? '');
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { userId, orgId, orgRole } = getAuth(req);
  if (!userId || !orgId) return res.status(401).json({ error: 'Unauthorized' });
  if (!isAdmin(orgRole)) return res.status(403).json({ error: 'Admin access required' });

  const prisma = getTenantPrisma(orgId);

  if (req.method === 'GET') {
    const page = parseInt(req.query['page'] as string ?? '1', 10);
    const limit = parseInt(req.query['limit'] as string ?? '25', 10);

    const [items, total] = await prisma.$transaction([
      (prisma as any)['{{TABLE_NAME}}'].findMany({
        skip: (page - 1) * limit,
        take: limit,
        orderBy: { createdAt: 'desc' },
      }),
      (prisma as any)['{{TABLE_NAME}}'].count(),
    ]);

    return res.status(200).json({
      data: items,
      meta: { page, limit, total, totalPages: Math.ceil(total / limit) },
    });
  }

  if (req.method === 'POST') {
    const item = await (prisma as any)['{{TABLE_NAME}}'].create({
      data: { ...req.body, tenantId: orgId },
    });
    // Audit log
    await writeAuditLog(prisma, { userId, orgId, action: 'create', entity: '{{TABLE_NAME}}', entityId: item.id });
    return res.status(201).json({ data: item });
  }

  return res.status(405).json({ error: 'Method not allowed' });
}

async function writeAuditLog(prisma: any, entry: { userId: string; orgId: string; action: string; entity: string; entityId: string }) {
  try {
    await prisma.auditLog?.create({ data: { ...entry, timestamp: new Date() } });
  } catch {
    // auditLog table may not exist in all apps — fail silently
  }
}
`;

export const adminAuditLogTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
import type { NextApiRequest, NextApiResponse } from 'next';
import { getAuth } from '@clerk/nextjs/server';
import { getTenantPrisma } from '@/lib/db/tenant';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed' });

  const { userId, orgId, orgRole } = getAuth(req);
  if (!userId || !orgId) return res.status(401).json({ error: 'Unauthorized' });
  if (!['admin', 'super_admin'].includes(orgRole ?? '')) {
    return res.status(403).json({ error: 'Admin access required' });
  }

  const prisma = getTenantPrisma(orgId);
  const page = parseInt(req.query['page'] as string ?? '1', 10);
  const limit = parseInt(req.query['limit'] as string ?? '50', 10);
  const entity = req.query['entity'] as string | undefined;

  try {
    const where = entity ? { entity } : {};
    const [logs, total] = await prisma.$transaction([
      (prisma as any).auditLog.findMany({
        where,
        skip: (page - 1) * limit,
        take: limit,
        orderBy: { timestamp: 'desc' },
      }),
      (prisma as any).auditLog.count({ where }),
    ]);

    return res.status(200).json({ data: logs, meta: { page, limit, total } });
  } catch {
    // auditLog table may not exist
    return res.status(200).json({ data: [], meta: { page, limit, total: 0 } });
  }
}
`;
