// packages/templates/src/loader/code-generator.ts
// ─── Code Generator — converts AppSpec entities/fields into code strings ───

import type { EntityDef, FieldDef, FieldType } from '../types/app-spec.js';

// ─── Prisma schema generation ──────────────────────────────────────────────────
export function generatePrismaModel(entity: EntityDef): string {
  const lines: string[] = [`model ${entity.name} {`];

  // Auto fields
  lines.push(`  id        String   @id @default(cuid())`);
  if (entity.tenantScoped) {
    lines.push(`  tenantId  String`);
  }

  for (const field of entity.fields) {
    if (field.name === 'id') continue; // already added
    lines.push(`  ${formatPrismaField(field)}`);
  }

  if (entity.timestamps !== false) {
    lines.push(`  createdAt DateTime @default(now())`);
    lines.push(`  updatedAt DateTime @updatedAt`);
  }

  if (entity.softDelete) {
    lines.push(`  deletedAt DateTime?`);
  }

  if (entity.tenantScoped) {
    lines.push(``);
    lines.push(`  @@index([tenantId])`);
  }

  lines.push(`}`);
  return lines.join('\n');
}

function formatPrismaField(field: FieldDef): string {
  const prismaType = fieldTypeToPrisma(field.type);
  const optional = field.required ? '' : '?';
  const modifiers: string[] = [];

  if (field.unique) modifiers.push('@unique');
  if (field.default !== undefined) {
    modifiers.push(`@default(${formatPrismaDefault(field.default, field.type)})`);
  }
  if (field.type === 'enum') {
    modifiers.push(`// enum: ${field.enumValues?.join(' | ')}`);
  }

  const modifier = modifiers.length ? '  ' + modifiers.join(' ') : '';
  return `  ${field.name.padEnd(20)} ${(prismaType + optional).padEnd(16)}${modifier}`;
}

function fieldTypeToPrisma(type: FieldType): string {
  const map: Record<FieldType, string> = {
    string: 'String',
    text: 'String',
    number: 'Float',
    boolean: 'Boolean',
    date: 'DateTime',
    datetime: 'DateTime',
    email: 'String',
    url: 'String',
    enum: 'String',
    relation: 'String', // FK — relation lines handled separately
    file: 'String',     // stored as URL/key
    json: 'Json',
  };
  return map[type] ?? 'String';
}

function formatPrismaDefault(value: unknown, type: FieldType): string {
  if (type === 'boolean') return String(value);
  if (type === 'number') return String(value);
  if (typeof value === 'string') return `"${value}"`;
  return String(value);
}

export function generateFullPrismaSchema(entities: EntityDef[], tenantId?: string): string {
  const header = `// Auto-generated by OneAtlas Template Engine
// DO NOT EDIT — changes will be overwritten on next generation

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
`;
  const models = entities.map(generatePrismaModel).join('\n\n');
  return `${header}\n${models}\n`;
}

// ─── Zod schema generation ────────────────────────────────────────────────────
export function generateZodSchema(entity: EntityDef): string {
  const fields = entity.fields
    .filter((f) => f.name !== 'id')
    .map((f) => `  ${f.name}: ${fieldTypeToZod(f)},`)
    .join('\n');

  return `import { z } from 'zod';

export const ${entity.name}Schema = z.object({
${fields}
});

export type ${entity.name}Input = z.infer<typeof ${entity.name}Schema>;
export type ${entity.name}Partial = Partial<${entity.name}Input>;
`;
}

function fieldTypeToZod(field: FieldDef): string {
  let base = '';
  switch (field.type) {
    case 'string':
    case 'text':
      base = 'z.string()';
      if (field.validation?.min) base += `.min(${field.validation.min})`;
      if (field.validation?.max) base += `.max(${field.validation.max})`;
      if (field.validation?.pattern) base += `.regex(/${field.validation.pattern}/)`;
      break;
    case 'email':
      base = 'z.string().email()';
      break;
    case 'url':
      base = 'z.string().url()';
      break;
    case 'number':
      base = 'z.number()';
      if (field.validation?.min) base += `.min(${field.validation.min})`;
      if (field.validation?.max) base += `.max(${field.validation.max})`;
      break;
    case 'boolean':
      base = 'z.boolean()';
      break;
    case 'date':
    case 'datetime':
      base = 'z.string().datetime()';
      break;
    case 'enum':
      if (field.enumValues?.length) {
        const vals = field.enumValues.map((v) => `'${v}'`).join(', ');
        base = `z.enum([${vals}])`;
      } else {
        base = 'z.string()';
      }
      break;
    case 'json':
      base = 'z.record(z.unknown())';
      break;
    case 'file':
    case 'relation':
      base = 'z.string()';
      break;
    default:
      base = 'z.string()';
  }

  if (!field.required) base += '.optional()';
  if (field.default !== undefined) {
    const defaultVal = typeof field.default === 'string' ? `'${field.default}'` : String(field.default);
    base += `.default(${defaultVal})`;
  }

  return base;
}

// ─── TypeScript interface generation ─────────────────────────────────────────
export function generateTypeScriptInterface(entity: EntityDef): string {
  const fields = entity.fields
    .map((f) => {
      const tsType = fieldTypeToTypeScript(f.type);
      const optional = f.required ? '' : '?';
      return `  ${f.name}${optional}: ${tsType};`;
    })
    .join('\n');

  const systemFields = [
    `  id: string;`,
    entity.tenantScoped ? `  tenantId: string;` : null,
    entity.timestamps !== false ? `  createdAt: Date;` : null,
    entity.timestamps !== false ? `  updatedAt: Date;` : null,
    entity.softDelete ? `  deletedAt?: Date | null;` : null,
  ]
    .filter(Boolean)
    .join('\n');

  return `export interface ${entity.name} {
${systemFields}
${fields}
}
`;
}

function fieldTypeToTypeScript(type: FieldType): string {
  const map: Record<FieldType, string> = {
    string: 'string',
    text: 'string',
    number: 'number',
    boolean: 'boolean',
    date: 'Date',
    datetime: 'Date',
    email: 'string',
    url: 'string',
    enum: 'string',
    relation: 'string',
    file: 'string',
    json: 'Record<string, unknown>',
  };
  return map[type] ?? 'string';
}

// ─── Slot value computation ───────────────────────────────────────────────────
export function computeSlotValues(entity: EntityDef): Record<string, string> {
  return {
    ENTITY_NAME: entity.name,
    ENTITY_NAME_PLURAL: entity.pluralName,
    TABLE_NAME: entity.tableName,
    FIELD_LIST: entity.fields.map((f) => f.name).join(', '),
    PRISMA_FIELDS: entity.fields.map(formatPrismaField).join('\n'),
    ZOD_SCHEMA: generateZodSchema(entity),
    TABLE_COLUMNS: generateTableColumns(entity),
    FORM_FIELDS: generateFormFields(entity),
    ROUTE_PATH: `/api/${entity.tableName}`,
  };
}

function generateTableColumns(entity: EntityDef): string {
  return entity.fields
    .filter((f) => !f.ui?.hidden)
    .slice(0, 6) // limit visible columns
    .map(
      (f) => `  { key: '${f.name}', label: '${f.label}', sortable: true }`
    )
    .join(',\n');
}

function generateFormFields(entity: EntityDef): string {
  return entity.fields
    .filter((f) => !f.ui?.hidden && !f.ui?.readOnly && f.name !== 'id')
    .map((f) => {
      const inputType = fieldTypeToInputType(f.type);
      return `  <FormField name="${f.name}" label="${f.label}" type="${inputType}" required={${f.required}} />`;
    })
    .join('\n');
}

function fieldTypeToInputType(type: FieldType): string {
  const map: Record<FieldType, string> = {
    string: 'text',
    text: 'textarea',
    number: 'number',
    boolean: 'checkbox',
    date: 'date',
    datetime: 'datetime-local',
    email: 'email',
    url: 'url',
    enum: 'select',
    relation: 'select',
    file: 'file',
    json: 'textarea',
  };
  return map[type] ?? 'text';
}
