// packages/templates/src/loader/component-registry.ts
// Generates the component registry module that is written into the built app.
// Provides lazy-loaded component maps keyed by entity name so page shells
// can render the correct components without hardcoded per-entity imports.

import type { AppSpec, EntityDef } from '../types/app-spec.js';

export interface ComponentRegistryEntry {
  entityName: string;
  tableName: string;
  components: {
    ListPage: string;     // import path
    DetailPage: string;
    FormPage: string;
  };
  apiPath: string;
}

// Generates the registry TypeScript module as a string.
// This string is written to `lib/registry.ts` inside the generated app.
export function generateComponentRegistryModule(spec: AppSpec): string {
  const entries = spec.entities.map(buildRegistryEntry);

  const lazyImports = entries
    .map(({ entityName, components }) => {
      return `  ${entityName}: {
    ListPage: React.lazy(() => import('../pages/${entityName.toLowerCase()}/index')),
    DetailPage: React.lazy(() => import('../pages/${entityName.toLowerCase()}/[id]')),
    FormPage: React.lazy(() => import('../pages/${entityName.toLowerCase()}/new')),
  },`;
    })
    .join('\n');

  const apiPaths = entries
    .map(({ entityName, apiPath }) => `  ${entityName}: '${apiPath}',`)
    .join('\n');

  const tableNames = entries
    .map(({ entityName, tableName }) => `  ${entityName}: '${tableName}',`)
    .join('\n');

  return `// Auto-generated by OneAtlas Template Engine — do not edit
import React from 'react';

// Component type shared across all entity pages
export interface EntityPageProps {
  entityName: string;
  params?: Record<string, string>;
}

// Lazy-loaded page components, keyed by entity name
export const ENTITY_COMPONENTS: Record<
  string,
  {
    ListPage: React.LazyExoticComponent<React.ComponentType<EntityPageProps>>;
    DetailPage: React.LazyExoticComponent<React.ComponentType<EntityPageProps>>;
    FormPage: React.LazyExoticComponent<React.ComponentType<EntityPageProps>>;
  }
> = {
${lazyImports}
};

// API base paths per entity
export const ENTITY_API_PATHS: Record<string, string> = {
${apiPaths}
};

// Table names per entity (for display and URL routing)
export const ENTITY_TABLE_NAMES: Record<string, string> = {
${tableNames}
};

// All registered entity names
export const ENTITY_NAMES = ${JSON.stringify(entries.map((e) => e.entityName))} as const;
export type EntityName = typeof ENTITY_NAMES[number];

// Resolve entity name from URL table name
export function resolveEntityFromTable(tableName: string): EntityName | null {
  const entry = ENTITY_NAMES.find((name) => ENTITY_TABLE_NAMES[name] === tableName);
  return entry ?? null;
}

// Get components for an entity — throws if entity not registered
export function getEntityComponents(entityName: string) {
  const components = ENTITY_COMPONENTS[entityName];
  if (!components) throw new Error(\`Entity not registered: \${entityName}\`);
  return components;
}
`;
}

// Also generates the dynamic page shell that uses the registry.
// Written to `pages/[entity]/index.tsx` in the generated app.
export function generateDynamicListPageShell(): string {
  return `// Auto-generated by OneAtlas Template Engine — do not edit
import React, { Suspense } from 'react';
import { useRouter } from 'next/router';
import { resolveEntityFromTable, getEntityComponents } from '../../lib/registry';

export default function DynamicListPage() {
  const router = useRouter();
  const tableName = router.query['entity'] as string | undefined;

  if (!tableName) return null;

  const entityName = resolveEntityFromTable(tableName);
  if (!entityName) return <div>Unknown entity: {tableName}</div>;

  const { ListPage } = getEntityComponents(entityName);

  return (
    <Suspense fallback={<div>Loading…</div>}>
      <ListPage entityName={entityName} />
    </Suspense>
  );
}
`;
}

// Generates the dynamic detail page shell.
// Written to `pages/[entity]/[id].tsx` in the generated app.
export function generateDynamicDetailPageShell(): string {
  return `// Auto-generated by OneAtlas Template Engine — do not edit
import React, { Suspense } from 'react';
import { useRouter } from 'next/router';
import { resolveEntityFromTable, getEntityComponents } from '../../lib/registry';

export default function DynamicDetailPage() {
  const router = useRouter();
  const tableName = router.query['entity'] as string | undefined;
  const id = router.query['id'] as string | undefined;

  if (!tableName || !id) return null;

  const entityName = resolveEntityFromTable(tableName);
  if (!entityName) return <div>Unknown entity: {tableName}</div>;

  const { DetailPage } = getEntityComponents(entityName);

  return (
    <Suspense fallback={<div>Loading…</div>}>
      <DetailPage entityName={entityName} params={{ id }} />
    </Suspense>
  );
}
`;
}

// Generates the dynamic form page shell.
// Written to `pages/[entity]/new.tsx` in the generated app.
export function generateDynamicFormPageShell(): string {
  return `// Auto-generated by OneAtlas Template Engine — do not edit
import React, { Suspense } from 'react';
import { useRouter } from 'next/router';
import { resolveEntityFromTable, getEntityComponents } from '../../lib/registry';

export default function DynamicFormPage() {
  const router = useRouter();
  const tableName = router.query['entity'] as string | undefined;

  if (!tableName) return null;

  const entityName = resolveEntityFromTable(tableName);
  if (!entityName) return <div>Unknown entity: {tableName}</div>;

  const { FormPage } = getEntityComponents(entityName);

  return (
    <Suspense fallback={<div>Loading…</div>}>
      <FormPage entityName={entityName} />
    </Suspense>
  );
}
`;
}

// Internal helper — builds one registry entry from an EntityDef
function buildRegistryEntry(entity: EntityDef): ComponentRegistryEntry {
  const name = entity.name;
  const table = entity.tableName;
  return {
    entityName: name,
    tableName: table,
    components: {
      ListPage: `../pages/${name.toLowerCase()}/index`,
      DetailPage: `../pages/${name.toLowerCase()}/[id]`,
      FormPage: `../pages/${name.toLowerCase()}/new`,
    },
    apiPath: `/api/${table}`,
  };
}
