// packages/templates/src/loader/hydration.ts
// Generates a hydration manifest that is embedded into the built app.
// The frontend reads this at runtime to know entity shapes, API paths,
// field types, and page routes without re-running the spec engine.

import type { AppSpec, EntityDef, FieldDef } from '../types/app-spec.js';

// Shape of each entity entry in the manifest
export interface HydrationEntity {
  name: string;
  pluralName: string;
  tableName: string;
  apiPath: string;          // e.g. /api/customers
  pages: {
    list: string;           // e.g. /customers
    detail: string;         // e.g. /customers/[id]
    form: string;           // e.g. /customers/new
  };
  fields: HydrationField[];
  tenantScoped: boolean;
  softDelete: boolean;
}

export interface HydrationField {
  name: string;
  label: string;
  type: FieldDef['type'];
  required: boolean;
  unique: boolean;
  inputType: string;        // HTML input type for forms
  showInTable: boolean;
  showInForm: boolean;
  enumValues?: string[];
}

export interface HydrationManifest {
  appId: string;
  appName: string;
  appType: AppSpec['appType'];
  tenantId: string;
  generatedAt: string;
  entities: HydrationEntity[];
  routes: { method: string; path: string }[];
  roles: string[];
}

// Main export — call this after spec is finalised
export function generateHydrationManifest(spec: AppSpec): HydrationManifest {
  return {
    appId: spec.id,
    appName: spec.name,
    appType: spec.appType,
    tenantId: spec.tenantId,
    generatedAt: new Date().toISOString(),
    entities: spec.entities.map(buildEntityEntry),
    routes: spec.routes.map((r) => ({ method: r.method, path: r.path })),
    roles: spec.permissions.roles.map((r) => r.name),
  };
}

// Serialise to JSON string for embedding in the bundle
export function serializeHydrationManifest(manifest: HydrationManifest): string {
  return JSON.stringify(manifest, null, 2);
}

// Generate the TypeScript module that wraps the manifest for tree-shaking
export function generateHydrationModule(manifest: HydrationManifest): string {
  const json = JSON.stringify(manifest);
  return `// Auto-generated by OneAtlas Template Engine — do not edit
// This file is re-generated on every spec change.

import type { HydrationManifest } from '@oneatlas/templates/loader';

export const APP_MANIFEST: HydrationManifest = ${json} as const;

export function getEntity(name: string) {
  return APP_MANIFEST.entities.find((e) => e.name === name) ?? null;
}

export function getEntityByTable(tableName: string) {
  return APP_MANIFEST.entities.find((e) => e.tableName === tableName) ?? null;
}

export function getTableFields(entityName: string) {
  const entity = getEntity(entityName);
  return entity?.fields.filter((f) => f.showInTable) ?? [];
}

export function getFormFields(entityName: string) {
  const entity = getEntity(entityName);
  return entity?.fields.filter((f) => f.showInForm) ?? [];
}
`;
}

// Build one entity entry from an EntityDef
function buildEntityEntry(entity: EntityDef): HydrationEntity {
  return {
    name: entity.name,
    pluralName: entity.pluralName,
    tableName: entity.tableName,
    apiPath: `/api/${entity.tableName}`,
    pages: {
      list: `/${entity.tableName}`,
      detail: `/${entity.tableName}/[id]`,
      form: `/${entity.tableName}/new`,
    },
    fields: entity.fields.map(buildFieldEntry),
    tenantScoped: entity.tenantScoped ?? false,
    softDelete: entity.softDelete ?? false,
  };
}

function buildFieldEntry(field: FieldDef): HydrationField {
  const entry: HydrationField = {
    name: field.name,
    label: field.label,
    type: field.type,
    required: field.required ?? false,
    unique: field.unique ?? false,
    inputType: fieldTypeToInputType(field.type),
    showInTable: !(field.ui?.hidden ?? false),
    showInForm: !(field.ui?.hidden ?? false) && !(field.ui?.readOnly ?? false) && field.name !== 'id',
  };
  if (field.enumValues !== undefined) {
    entry.enumValues = field.enumValues;
  }
  return entry;
}

function fieldTypeToInputType(type: FieldDef['type']): string {
  const map: Record<FieldDef['type'], string> = {
    string: 'text',
    text: 'textarea',
    number: 'number',
    boolean: 'checkbox',
    date: 'date',
    datetime: 'datetime-local',
    email: 'email',
    url: 'url',
    enum: 'select',
    relation: 'select',
    file: 'file',
    json: 'textarea',
  };
  return map[type] ?? 'text';
}