// packages/templates/src/loader/index.ts
// ─── Template Loader — resolves template, hydrates slots, produces GeneratedFiles ───

import { resolveTemplate, getTemplate } from '../registry/index.js';
import { computeSlotValues, generateFullPrismaSchema } from './code-generator.js';
import { generateFileFromTemplate, smartPatch, resolveFilePath, sha256 } from './ast-patcher.js';
import { listCreateTemplate, getUpdateDeleteTemplate } from '../registry/templates/crud/api/handlers.js';
import type { AppSpec } from '../types/app-spec.js';
import { generateHydrationManifest, generateHydrationModule } from './hydration.js';
import { generateComponentRegistryModule, generateDynamicListPageShell, generateDynamicDetailPageShell, generateDynamicFormPageShell } from './component-registry.js';
import type { RenderManifest, GeneratedFile } from '../types/render-manifest.js';

// ─── Template source map — maps templateSource key → actual template string ───
const TEMPLATE_SOURCES: Record<string, string> = {
  'crud/api/list-create': listCreateTemplate,
  'crud/api/get-update-delete': getUpdateDeleteTemplate,
  // Add more as templates expand
};

function getTemplateSource(key: string): string {
  const src = TEMPLATE_SOURCES[key];
  if (!src) throw new Error(`Template source not found: ${key}`);
  return src;
}

// ─── Main loader function ─────────────────────────────────────────────────────
export async function loadTemplate(
  spec: AppSpec,
  existingManifest?: RenderManifest
): Promise<RenderManifest> {
  const template = resolveTemplate(spec.appType, spec.entities.length);
  const allFiles: GeneratedFile[] = [];

  // Generate files for each entity
  for (const entity of spec.entities) {
    const slotValues = computeSlotValues(entity);

    for (const templateFile of template.files) {
      const templateSource = getTemplateSource(templateFile.templateSource);
      const resolvedPath = resolveFilePath(templateFile.relativePath, slotValues);

      // Check if file exists in prior manifest
      const existing = existingManifest?.files.find((f) => f.relativePath === resolvedPath);

      if (existing) {
        // Smart patch: preserve user edits, only update changed slots
        const patched = smartPatch(existing, slotValues, templateSource);
        allFiles.push(patched);
      } else {
        // Fresh generation
        const generated = generateFileFromTemplate(
          templateSource,
          slotValues,
          templateFile.relativePath,
          template.id
        );
        allFiles.push(generated);
      }
    }
  }

  // Generate Prisma schema
  const prismaSchema = generateFullPrismaSchema(spec.entities);

  // Add prisma schema file
  allFiles.push({
    relativePath: 'prisma/schema.prisma',
    content: prismaSchema,
    origin: 'composed',
    templateId: template.id,
    hash: sha256(prismaSchema),
    generatedAt: new Date().toISOString(),
    lockedFromRegen: false,
  });

  // Add tenant DB utility
  allFiles.push({
    relativePath: 'lib/db/tenant.ts',
    content: generateTenantPrismaUtil(),
    origin: 'composed',
    templateId: template.id,
    hash: sha256(generateTenantPrismaUtil()),
    generatedAt: new Date().toISOString(),
    lockedFromRegen: false,
  });

  // Add RBAC middleware
  allFiles.push({
    relativePath: 'middleware.ts',
    content: generateRBACMiddleware(spec),
    origin: 'composed',
    templateId: template.id,
    hash: sha256(generateRBACMiddleware(spec)),
    generatedAt: new Date().toISOString(),
    lockedFromRegen: false,
  });

  const manifest: RenderManifest = {
    appId: spec.id,
    tenantId: spec.tenantId,
    templateId: template.id,
    version: (existingManifest?.version ?? 0) + 1,
    files: allFiles,
    prismaSchema,
    envVarKeys: template.envVars,
    routes: spec.routes.map((r) => ({
      method: r.method,
      path: r.path,
      handlerFile: `pages/api${r.path.replace(/^\/api/, '')}.ts`,
    })),
    pages: spec.pages.map((p) => ({
      path: p.path,
      componentFile: `pages${p.path}/index.tsx`,
    })),
    generatedAt: new Date().toISOString(),
    bundleReady: false,
  };

  return manifest;
}

// ─── Tenant Prisma utility ────────────────────────────────────────────────────
function generateTenantPrismaUtil(): string {
  return `// Auto-generated by OneAtlas Template Engine
import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as { prismaClients: Map<string, PrismaClient> };
if (!globalForPrisma.prismaClients) {
  globalForPrisma.prismaClients = new Map();
}

export function getTenantPrisma(tenantId: string): PrismaClient {
  const cached = globalForPrisma.prismaClients.get(tenantId);
  if (cached) return cached;

  const client = new PrismaClient({
    datasources: { db: { url: process.env['DATABASE_URL'] } },
  });

  // Set search_path for schema-per-tenant isolation
  const tenantClient = client.$extends({
    query: {
      $allModels: {
        async $allOperations({ args, query }) {
          await client.$executeRawUnsafe(\`SET search_path = "tenant_\${tenantId}"\`);
          return query(args);
        },
      },
    },
  }) as unknown as PrismaClient;

  globalForPrisma.prismaClients.set(tenantId, tenantClient);
  return tenantClient;
}
`;
}

// ─── RBAC middleware ──────────────────────────────────────────────────────────
function generateRBACMiddleware(spec: AppSpec): string {
  const roleList = spec.permissions.roles.map((r) => r.name);
  return `// Auto-generated by OneAtlas Template Engine
import { clerkMiddleware, createRouteMatcher } from '@clerk/nextjs/server';
import { NextResponse } from 'next/server';

const isPublicRoute = createRouteMatcher(['/sign-in(.*)', '/sign-up(.*)']);
const isApiRoute = createRouteMatcher(['/api(.*)']);

const ROLES = ${JSON.stringify(roleList)} as const;
type Role = typeof ROLES[number];

export default clerkMiddleware(async (auth, req) => {
  if (isPublicRoute(req)) return NextResponse.next();

  const { userId, orgId, orgRole } = await auth();

  if (!userId) return NextResponse.redirect(new URL('/sign-in', req.url));
  if (isApiRoute(req) && !orgId) {
    return NextResponse.json({ error: 'Organization required' }, { status: 403 });
  }

  return NextResponse.next();
});

export const config = {
  matcher: ['/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)'],
};
`;
}

// ─── Hydration & Component Registry wiring ───────────────────────────────────
// Call this after loadTemplate to get all generated app files including
// the hydration manifest and component registry.
export function generateAppShellFiles(spec: AppSpec, templateId: string): GeneratedFile[] {
  const now = new Date().toISOString();

  const hydrationManifest = generateHydrationManifest(spec);
  const hydrationModule = generateHydrationModule(hydrationManifest);
  const registryModule = generateComponentRegistryModule(spec);

  const make = (relativePath: string, content: string): GeneratedFile => ({
    relativePath,
    content,
    origin: 'composed' as const,
    templateId,
    hash: sha256(content),
    generatedAt: now,
    lockedFromRegen: false,
  });

  return [
    make('lib/hydration-manifest.json', JSON.stringify(hydrationManifest, null, 2)),
    make('lib/manifest.ts', hydrationModule),
    make('lib/registry.ts', registryModule),
    make('pages/[entity]/index.tsx', generateDynamicListPageShell()),
    make('pages/[entity]/[id].tsx', generateDynamicDetailPageShell()),
    make('pages/[entity]/new.tsx', generateDynamicFormPageShell()),
  ];
}
