// packages/templates/src/registry/templates/dashboard/pages/index.ts

export const dashboardMainTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
'use client';
import React from 'react';
import useSWR from 'swr';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar } from 'recharts';

interface StatsResponse {
  kpis: Record<string, number>;
  timeSeries: { date: string; value: number }[];
  recentItems: Record<string, unknown>[];
  total: number;
}

const fetcher = (url: string) => fetch(url).then((r) => r.json());

function KpiCard({ label, value }: { label: string; value: number | string }) {
  return (
    <div className="bg-white rounded-lg border border-gray-200 p-5">
      <p className="text-sm text-gray-500 font-medium">{label}</p>
      <p className="text-3xl font-semibold text-gray-900 mt-1">{typeof value === 'number' ? value.toLocaleString() : value}</p>
    </div>
  );
}

export default function {{ENTITY_NAME}}Dashboard() {
  const { data, isLoading } = useSWR<StatsResponse>('/api/dashboard/stats', fetcher, { refreshInterval: 30000 });

  if (isLoading) return <div className="p-6 text-gray-500">Loading dashboard…</div>;

  const kpis = data?.kpis ?? {};
  const timeSeries = data?.timeSeries ?? [];

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-semibold text-gray-900">{{ENTITY_NAME}} Analytics</h1>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {Object.entries(kpis).map(([key, val]) => (
          <KpiCard key={key} label={key.replace(/_/g, ' ')} value={val} />
        ))}
        <KpiCard label="Total Records" value={data?.total ?? 0} />
      </div>

      {/* Time Series Chart */}
      {timeSeries.length > 0 && (
        <div className="bg-white rounded-lg border border-gray-200 p-5">
          <h2 className="text-lg font-medium text-gray-800 mb-4">Trend Over Time</h2>
          <ResponsiveContainer width="100%" height={240}>
            <LineChart data={timeSeries}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis dataKey="date" tick={{ fontSize: 12 }} />
              <YAxis tick={{ fontSize: 12 }} />
              <Tooltip />
              <Line type="monotone" dataKey="value" stroke="#6366f1" strokeWidth={2} dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      )}

      {/* Recent Items Table */}
      {data?.recentItems && data.recentItems.length > 0 && (
        <div className="bg-white rounded-lg border border-gray-200 p-5">
          <h2 className="text-lg font-medium text-gray-800 mb-4">Recent {{ENTITY_NAME}} Records</h2>
          <div className="overflow-x-auto">
            <table className="min-w-full text-sm divide-y divide-gray-100">
              <thead>
                <tr>
                  {Object.keys(data.recentItems[0]!).slice(0, 5).map((col) => (
                    <th key={col} className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">{col}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {data.recentItems.map((row, i) => (
                  <tr key={i}>
                    {Object.values(row).slice(0, 5).map((val, j) => (
                      <td key={j} className="px-3 py-2 text-gray-700">{String(val ?? '—')}</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
`;
