// packages/templates/src/registry/templates/dashboard/api/index.ts

export const dashboardStatsTemplate = `// Auto-generated by OneAtlas Template Engine — do not edit
import type { NextApiRequest, NextApiResponse } from 'next';
import { getAuth } from '@clerk/nextjs/server';
import { getTenantPrisma } from '@/lib/db/tenant';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed' });

  const { userId, orgId } = getAuth(req);
  if (!userId || !orgId) return res.status(401).json({ error: 'Unauthorized' });

  const prisma = getTenantPrisma(orgId);

  try {
    // Total count
    const total = await (prisma as any)['{{TABLE_NAME}}'].count();

    // KPI aggregates — numeric fields
    const all = await (prisma as any)['{{TABLE_NAME}}'].findMany({
      select: { {{KPI_FIELDS}}: true, {{TIME_FIELD}}: true },
      orderBy: { {{TIME_FIELD}}: 'desc' },
      take: 500,
    });

    // Compute KPIs: sum and avg of numeric fields
    const kpis: Record<string, number> = {};
    const numericKeys = ['{{KPI_FIELDS}}'].filter(Boolean);
    for (const key of numericKeys) {
      const values = all.map((r: any) => Number(r[key] ?? 0)).filter(isFinite);
      if (values.length) {
        kpis[\`total_\${key}\`] = values.reduce((a: number, b: number) => a + b, 0);
        kpis[\`avg_\${key}\`] = Math.round(kpis[\`total_\${key}\`]! / values.length);
      }
    }

    // Time series — group by day on {{TIME_FIELD}}
    const buckets: Record<string, number> = {};
    for (const row of all) {
      const date = row['{{TIME_FIELD}}'] ? new Date(row['{{TIME_FIELD}}']).toISOString().slice(0, 10) : null;
      if (date) buckets[date] = (buckets[date] ?? 0) + 1;
    }
    const timeSeries = Object.entries(buckets)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([date, value]) => ({ date, value }));

    // Recent items
    const recentItems = await (prisma as any)['{{TABLE_NAME}}'].findMany({
      take: 10,
      orderBy: { createdAt: 'desc' },
    });

    return res.status(200).json({ kpis, timeSeries, recentItems, total });
  } catch (error) {
    console.error('Dashboard stats error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
}
`;
